### ISSUE TITLE
Please provide a readme.md

### ISSUE THREAD

**Issue by JafarAkhondali** [boostget/BoostGet#1]
Dear Javid,
Can you provide a readme about this program and what does it do?
Is it an dlm?

**Comment by javidsho** [comment]
Hi Jafar!
Thank you for your interest.
It’s just a draft and it’s nothing serious for now. I haven’t decided if I want to continue the project or not, but yes, it was supposed to be a DLM library.

**Comment by JafarAkhondali** [comment]
Thanks, btw have you checked [Aria2](https://github.com/aria2/aria2) ?

**Comment by javidsho** [comment]
Yes I have. That's why I might delete this project.
